title: "Oblogatory"
description: My obligatory blog. Notes on books, music, Gentoo, and skating.
google_analytics: UA-63523632-2
show_downloads: false
show_excerpts: true

theme: minima

github:
  is_project_page: false
  is_user_page: true

author: Andrew Hamlin
email: aahamlin@gmail.com

header_pages:
  - index.md
  - manager_readme.md
  - about.md
  
github_username: aahamlin
instagram_username: andrewhamlin
# bitbucket_username: andrew_hamlin
twitter_username: ahamlinSWeng
linkedin_username: andrewahamlin
