title: Andrew A Hamlin
description: Software craftsmanship. Servant leadership. Trust. Respect. Integrity.
google_analytics: UA-63523632-2
show_downloads: false

#theme: jekyll-theme-minimal
theme: jekyll-theme-architect
#theme: jekyll-theme-slate
#theme: jekyll-theme-midnight

plugins:
  - jekyll-mentions

github:
  is_project_page: false
  is_user_page: true

email_address: aahamlin[at]gmail.com
linkedin_url: https://www.linkedin.com/in/andrewahamlin
linkedin_title: Profile
resume_url: /files/andrew_hamlin_resume.pdf
resume_title: Resume

