title: aahamlin.github.io
description: "\"The longest way 'round is the shortest way home.\" - Alexander MacLaren"
google_analytics: 
show_downloads: false
theme: jekyll-theme-minimal

plugins:
  - jekyll-mentions

email: aahamlin[at]gmail.com
linkedin_url: https://www.linkedin.com/in/andrewahamlin
resume_url: /files/andrew_hamlin_resume.pdf
resume_title: Andrew A Hamlin Resume
logo: /files/aahllc_logo.png
